### ISSUE TITLE
Pausing and resuming a track causes it to abruptly stop playing

### ISSUE THREAD

**Issue by karlsbjorn** [Drapersniper/PyLav#237]
**Describe the bug**
When pausing a track for a few minutes and then resuming it, the track will play as normal for a while and then abruptly stop.

**To Reproduce**
1. Pause a track for a few minutes
2. Resume the track
3. Wait anywhere from a few seconds to a minute before the track abruptly stops

**Expected behavior**
The resumed track plays all the way to the end as intended.

I have observed this only on the current release and don't know whether or not it happens on the v4 branch

**Comment by Drapersniper** [comment]
Similar can be observed with seek on Deezer tracks, although I haven't been able to reproduce the issue with seek/pause & resume reliably

P.s. This is not a library issue.

**Comment by karlsbjorn** [comment]
I can still repro this on the current release using the same steps

**Comment by Drapersniper** [comment]
Its not something pylav specific and it related to the deezer decoding and frames, there's nothing I can do pylav side
