### ISSUE TITLE
Song Titles are double escaped?

### ISSUE THREAD

**Issue by Kuro-Rui** [Drapersniper/PyLav#252]
**Describe the bug**
Every song title is double escaped. For example, Queencard - (G)I-DLE shows Queencard \- (G)I\-DLE.

**To Reproduce**
1. Use any command to queue a song / show the current playing song (For example, `[p]play https://deezer.com/track/2256532067`)
2. Title shows as double escaped

**Expected behavior**
Queencard \- (G)I\-DLE should show Queencard - (G)I-DLE (not double escaped)

**Screenshots**
![image](https://github.com/PyLav/PyLav/assets/83048873/78248602-52c2-4a07-9bab-11d7ff232f0d)

**Comment by Drapersniper** [comment]
![image](https://github.com/PyLav/PyLav/assets/27962761/5669cf54-faf2-4616-a229-892d1f13a19b)
Not reproducing this (Fresh install)
