### ISSUE TITLE
Says node not available, but it's right here

### ISSUE THREAD

**Issue by LeDeathAmongst** [Drapersniper/PyLav#322]
**Describe the bug**
Managed node states not available:
https://i.imgur.com/u1KQ8KU.png
But the lavalink is ready to accept notifications:
https://i.imgur.com/CCZgzrU.png

**To Reproduce**
1. N/A

**Expected behavior**
A managed lavlink node to work.

**Screenshots**
Did in the descrption
**Desktop (please complete the following information):**
 - OS: Neofetch results:
 https://i.imgur.com/kkRLrar.png
 
 EDIT
 ===
 Found out, if you set a `network_mode : host` in the docker-compose.yml (to allow dashboard) it breaks PyLav. I commented it to see if that's the cause, and it caused it.
 https://i.imgur.com/VzDHNlE.png <- commented it out
 https://i.imgur.com/bwTJMHl.png <- works since commented and restarted

**Comment by Drapersniper** [comment]
Whenever the environment is changed you need to make sure the config file is correctly updated.

The default config file assumes no changes from the instructions.
