### ISSUE TITLE
OS/Arch support status.

### ISSUE THREAD

**Issue by Drapersniper** [Drapersniper/PyLav#8]
<table>
<tr>
	<td> Platform
	<td> Arch/Model
	<td> OS Version
    <td> Status
<tr>
	<td> Linux
	<td> X64
	<td> 20.04
	<td> Working
<tr>
	<td> Linux
	<td> X64
	<td> 22.04
	<td> Working
<tr>
	<td> Mac
	<td> Intel
	<td> 12.3.1
	<td> Working
<tr>
	<td> Mac
	<td> M1
	<td> 11.6.5
	<td> Working
</table>

**Comment by aikaterna** [comment]
Works on an M1 with Mac OS Big Sur 11.6.5 with Brew-installed Python 3.10.4

**Comment by Drapersniper** [comment]
Should work on every arch supported by Postgres + Lavalink.
